name: Deploy to Vercel
on:
    push:
        branches:
            - main
jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: amondnet/vercel-action@v20
              with:
                  token: ${{ secrets.VERCEL_TOKEN }}
                  vercel-args: "--prod"
                  org: ${{ secrets.VERCEL_ORG_ID}}
                  projectId: ${{ secrets.VERCEL_PROJECT_ID}}
